spring.application.name=Your project name 
#Database Config

spring.datasource.url=jdbc:mysql://localhost:DataBase port number/ Your DataBase Name
spring.datasource.username=Your DataBase User Name
spring.datasource.password=Your DataBase Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

#Email sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Your Gamil Id
spring.mail.password=Your Gmail App Password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




